/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CityStatistic { 
    cityId?: string;
    cityName?: string;
    plateCode?: string;
    x?: number;
    y?: number;
    totalPolice?: number;
    activePolice?: number;
    overLimitPolice?: number;
    activePercent?: number;
    unitCount?: number;
}

