/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CityStatistic } from './cityStatistic';


export interface MapStatisticsResponse { 
    cities?: Array<CityStatistic>;
    totalPolice?: number;
    activePolice?: number;
    busiestCityName?: string;
    busiestCityActivePolice?: number;
}

