/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MenuItemModel { 
    code?: string;
    title?: string;
    path?: string;
    children?: Array<MenuItemModel>;
}

