/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PoliceSaveRequest { 
    id?: string;
    badgeNumber?: string;
    fullName?: string;
    age?: number;
    rank?: string;
    score?: number;
    phone?: string;
    startDate?: string;
    cityId?: string;
    unitId?: string;
    status?: string;
    taskType?: string;
    dailyTaskLimit?: number;
}

