/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PoliceDetailResponse { 
    found?: boolean;
    id?: string;
    badgeNumber?: string;
    fullName?: string;
    age?: number;
    rank?: string;
    score?: number;
    photoUrl?: string;
    phone?: string;
    startDate?: string;
    cityId?: string;
    cityName?: string;
    unitId?: string;
    unitName?: string;
    status?: string;
    statusName?: string;
    taskType?: string;
    taskTypeName?: string;
    dailyTaskCount?: number;
    dailyTaskLimit?: number;
    overDailyLimit?: boolean;
    vehiclePlate?: string;
}

