/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PoliceListItem { 
    id?: string;
    badgeNumber?: string;
    fullName?: string;
    rank?: string;
    cityName?: string;
    unitName?: string;
    status?: string;
    statusName?: string;
    taskTypeName?: string;
    score?: number;
    photoUrl?: string;
    overDailyLimit?: boolean;
}

