/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PoliceListItem } from './policeListItem';


export interface PoliceListResponse { 
    policeList?: Array<PoliceListItem>;
    totalCount?: number;
    pageNumber?: number;
    pageSize?: number;
}

