/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegionListItem } from './regionListItem';


export interface RegionListResponse { 
    regions?: Array<RegionListItem>;
    totalCount?: number;
}

