/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportTypeItem } from './reportTypeItem';


export interface ReportTypeListResponse { 
    types?: Array<ReportTypeItem>;
}

