/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportListItem } from './reportListItem';


export interface ReportListResponse { 
    reports?: Array<ReportListItem>;
    totalCount?: number;
}

