/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportEntryConfirmResponse { 
    valid?: boolean;
    reportName?: string;
    reportTypeName?: string;
    cityName?: string;
    unitName?: string;
    period?: string;
    policeCount?: number;
    taskCount?: number;
    message?: string;
}

