/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SettingResponse { 
    success?: boolean;
    language?: string;
    pageSize?: number;
    defaultCityId?: string;
    refreshSeconds?: number;
    message?: string;
}

