/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SettingSaveRequest { 
    token?: string;
    language?: string;
    pageSize?: number;
    defaultCityId?: string;
    refreshSeconds?: number;
}

