/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatusCount } from './statusCount';


export interface SummaryResponse { 
    totalPolice?: number;
    onDuty?: number;
    atStation?: number;
    onLeave?: number;
    onReport?: number;
    overDailyLimit?: number;
    unitCount?: number;
    statusDistribution?: Array<StatusCount>;
}

