/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskListItem { 
    id?: string;
    policeId?: string;
    policeName?: string;
    badgeNumber?: string;
    cityName?: string;
    unitName?: string;
    type?: string;
    typeName?: string;
    location?: string;
    startTime?: string;
    endTime?: string;
    status?: string;
    statusName?: string;
}

