/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrendPoint } from './trendPoint';


export interface TaskTrendResponse { 
    cityName?: string;
    points?: Array<TrendPoint>;
    totalTaskCount?: number;
    averageTaskCount?: number;
}

