/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskAssignConfirmResponse { 
    valid?: boolean;
    policeId?: string;
    policeName?: string;
    badgeNumber?: string;
    unitName?: string;
    cityName?: string;
    typeName?: string;
    location?: string;
    timeRange?: string;
    currentTaskCount?: number;
    dailyTaskLimit?: number;
    willExceedLimit?: boolean;
    message?: string;
}

