/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskListItem } from './taskListItem';


export interface TaskListResponse { 
    tasks?: Array<TaskListItem>;
    totalCount?: number;
    pageNumber?: number;
    pageSize?: number;
}

