/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskTypeItem } from './taskTypeItem';


export interface TaskTypeListResponse { 
    types?: Array<TaskTypeItem>;
    totalTaskCount?: number;
}

