/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskListRequest { 
    cityId?: string;
    unitId?: string;
    policeId?: string;
    type?: string;
    status?: string;
    onlyOverLimit?: boolean;
    pageNumber?: number;
    pageSize?: number;
}

