/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskAssignRequest { 
    policeId?: string;
    type?: string;
    location?: string;
    startTime?: string;
    endTime?: string;
}

