/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UnitListItem { 
    id?: string;
    name?: string;
    cityId?: string;
    cityName?: string;
}

