/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UnitWorkloadItem } from './unitWorkloadItem';


export interface UnitWorkloadResponse { 
    cityId?: string;
    cityName?: string;
    units?: Array<UnitWorkloadItem>;
    totalTaskLoad?: number;
}

