/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UnitWorkloadItem { 
    unitId?: string;
    unitName?: string;
    totalPolice?: number;
    activePolice?: number;
    taskLoad?: number;
    patrol?: number;
    radar?: number;
    motorcycle?: number;
    schoolCrossing?: number;
    accidentInvestigation?: number;
    loadPercent?: number;
}

