/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VehicleListRequest { 
    cityId?: string;
    unitId?: string;
    type?: string;
    searchText?: string;
    pageNumber?: number;
    pageSize?: number;
}

