/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehicleListItem } from './vehicleListItem';


export interface VehicleListResponse { 
    vehicles?: Array<VehicleListItem>;
    totalCount?: number;
    pageNumber?: number;
    pageSize?: number;
}

