/**
 * Simtek API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VehicleDetailResponse { 
    found?: boolean;
    plate?: string;
    policeId?: string;
    brand?: string;
    model?: string;
    modelYear?: number;
    type?: string;
    kilometers?: number;
    lastMaintenanceDate?: string;
    photoUrl?: string;
    unitName?: string;
    cityName?: string;
}

