
app.cors.allowed-origins=https://simtek.local

app.crypto.key=${SIMTEK_CRYPTO_KEY}

spring.datasource.url=${SIMTEK_DB_URL}
spring.datasource.username=${SIMTEK_DB_USER}
spring.datasource.password=${SIMTEK_DB_PASSWORD}

spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10

spring.jpa.show-sql=false
