export * from './analyticsController.service';
import { AnalyticsControllerService } from './analyticsController.service';
export * from './dashboardController.service';
import { DashboardControllerService } from './dashboardController.service';
export * from './loginController.service';
import { LoginControllerService } from './loginController.service';
export * from './policeController.service';
import { PoliceControllerService } from './policeController.service';
export * from './regionController.service';
import { RegionControllerService } from './regionController.service';
export * from './reportEntryController.service';
import { ReportEntryControllerService } from './reportEntryController.service';
export * from './resourceController.service';
import { ResourceControllerService } from './resourceController.service';
export * from './settingController.service';
import { SettingControllerService } from './settingController.service';
export * from './taskController.service';
import { TaskControllerService } from './taskController.service';
export * from './unitController.service';
import { UnitControllerService } from './unitController.service';
export * from './vehicleController.service';
import { VehicleControllerService } from './vehicleController.service';
export const APIS = [AnalyticsControllerService, DashboardControllerService, LoginControllerService, PoliceControllerService, RegionControllerService, ReportEntryControllerService, ResourceControllerService, SettingControllerService, TaskControllerService, UnitControllerService, VehicleControllerService];
